add Utils and testing
jtiradohernandez/homework-java-ironlibrary pull request #4
Opened 2024-03-16 11:52 UTC by DJH23

2024-03-16 12:01 UTC, ainafetse22 requested changes
Please add all changes before merging

2024-03-16 12:01 UTC, ainafetse22 commented on ironlibrary/src/main/java/com/example/ironlibrary/model/Issue.java
> +public class Issue implements InputValidator{
@NoArgsConstructor

2024-03-16 12:01 UTC, ainafetse22 commented on ironlibrary/src/main/java/com/example/ironlibrary/model/Utils.java
> +    public static long dateDifferenceCalculator(String startDate, String endDate) {
add String date format validation example DATE= "23/03/2024"

2024-03-16 12:01 UTC, ainafetse22 commented on ironlibrary/src/test/java/com/example/ironlibrary/UtilsTest.java
> +    void testIsbnValidator() {
Which is the real format of the ISBN?

2024-03-16 12:01 UTC, ainafetse22 commented on ironlibrary/src/main/java/com/example/ironlibrary/model/Utils.java
> +    public static int quantityUpdate(int currentQuantity, int change) {
change the name to addQuantity, if have no sense this way, will always be more than 0. You should validate that the change value is not negative only.

2024-03-16 12:01 UTC, ainafetse22 commented on ironlibrary/src/test/java/com/example/ironlibrary/UtilsTest.java
> +    void testQuantityUpdate() {
change the test accordingly

2024-03-16 12:01 UTC, ainafetse22 commented on ironlibrary/src/test/java/com/example/ironlibrary/UtilsTest.java
> +    void testDateDifferenceCalculator() {
add test for checking date format of each string.

2024-03-29 08:56 UTC, Katenokk commented on ironlibrary/src/main/resources/application.properties
> +
hay que dejar las properties originales

2024-04-02 19:53 UTC, closed without merging